### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by markwalet** [hosmelq/laravel-pulse-schedule#1]
Hi there, first of all a big thanks for creating and maintaining this package.

Laravel 11 will be released soon. So I think it's a good idea to include Laravel 11 support for this package. Let me know if you need any help on that.

**Comment by hosmelq** [comment]
Hello @markwalet, thank you for your kind words :). I will add L11 support this weekend.

**Comment by hosmelq** [comment]
Hello @markwalet, I just released the v0.2.0 version with L11 support.
